#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $TITAN_REPO == "titansbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1VTRVJCT1QtU1VQUE9SVC9USVRBTlMtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $TITAN_REPO == "TITANSBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1VTRVJCT1QtU1VQUE9SVC9USVRBTlMtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $TITAN_REPO =~ $regex ]]
    then
        if [[ $TITAN_REPO_BRANCH ]]
        then
            echo "${TITAN_REPO}/archive/${TITAN_REPO_BRANCH}.zip"
        else
            echo "${TITAN_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1VTRVJCT1QtU1VQUE9SVC9USVRBTlMtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="titansbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    TITANSPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $TITANSBOT
    echo "    Starting TitansBot    "
    echo "
                          ╔═╦═╦══╦══╦══╦══╦══╦═╦══╗
                          ║     TITANS                ╝
                          ║             BOT         
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚╩══╩═╝╚╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m TITAN
}

_set_bot
